#!/usr/bin/env bash
# Bump semver in backend/dronmakr/version.py (commit + tag + push), then create GitHub Release for that tag with gh CLI.
# Release notes are generated by the Cursor agent CLI from commits between the previous tag and the new tag.
#
# Prerequisites:
#   - gh authenticated (`gh auth login`)
#   - Cursor agent CLI logged in (`cursor agent login` or `agent login`)
#
# Usage:
#   ./scripts/bump_and_release.sh patch
#   ./scripts/bump_and_release.sh minor --dry-run
#   ./scripts/bump_and_release.sh patch -- --draft --title "Smoke test"
#   ./scripts/bump_and_release.sh patch --skip-ai-notes
#
# Extra args after -- are forwarded to `gh release create` (same as gh_release_latest_tag.sh).
#
# Env:
#   SKIP_AI_RELEASE_NOTES=1 — use gh --generate-notes instead of Cursor agent
#   CURSOR_AGENT_MODEL      — optional model for release-notes generation
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

VERSION_FILE="backend/dronmakr/version.py"
BUMP_TYPE=""
DRY_RUN=false
SKIP_AI_NOTES=false
PASS_THROUGH=()

usage() {
  echo "Usage: $(basename "$0") [major|minor|patch] [--dry-run] [--skip-ai-notes] [-- <gh-release-args>]"
  echo "Combines scripts/bump_version.sh, Cursor agent release notes, and gh release create."
}

generate_release_notes_file() {
  local prev_tag=$1
  local new_tag=$2
  local notes_file
  notes_file="$(mktemp "${TMPDIR:-/tmp}/dronmakr-release-notes.XXXXXX")"
  if "$ROOT_DIR/scripts/generate_release_notes.sh" "$prev_tag" "$new_tag" > "$notes_file"; then
    if [[ -s "$notes_file" ]]; then
      echo "$notes_file"
      return 0
    fi
  fi
  rm -f "$notes_file"
  return 1
}

while (($#)); do
  case "$1" in
    major | minor | patch)
      if [[ -n "$BUMP_TYPE" ]]; then
        echo "error: bump type already set to \"$BUMP_TYPE\"." >&2
        usage >&2
        exit 1
      fi
      BUMP_TYPE=$1
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --skip-ai-notes)
      SKIP_AI_NOTES=true
      shift
      ;;
    --)
      shift
      PASS_THROUGH+=("$@")
      break
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "error: Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$BUMP_TYPE" ]]; then
  usage >&2
  exit 1
fi

if [[ ! -f "$VERSION_FILE" ]]; then
  echo "error: ${VERSION_FILE} not found under ${ROOT_DIR}" >&2
  exit 1
fi

current_version=$(sed -nE 's/^__version__ *= *"([0-9]+\.[0-9]+\.[0-9]+)"/\1/p' "$VERSION_FILE")
IFS='.' read -r major minor patch <<< "$current_version"

case "$BUMP_TYPE" in
  major)
    ((major++))
    minor=0
    patch=0
    ;;
  minor)
    ((minor++))
    patch=0
    ;;
  patch)
    ((patch++))
    ;;
esac

new_version="${major}.${minor}.${patch}"
PREV_TAG="v${current_version}"
NEW_TAG="v${new_version}"

if [[ "${SKIP_AI_RELEASE_NOTES:-}" == "1" ]]; then
  SKIP_AI_NOTES=true
fi

echo "Bump type: ${BUMP_TYPE}"
echo "Current version: ${current_version}  (tag ${PREV_TAG})"
echo "Next version:   ${new_version}  (release tag ${NEW_TAG})"

if [[ "$DRY_RUN" == true ]]; then
  echo "[Dry run] Would run: scripts/bump_version.sh ${BUMP_TYPE}"
  if [[ "$SKIP_AI_NOTES" == true ]]; then
    echo "[Dry run] Would generate release notes: gh --generate-notes"
    CMD_PREVIEW=(gh release create "$NEW_TAG" --verify-tag --generate-notes --latest)
  else
    echo "[Dry run] Would generate release notes: scripts/generate_release_notes.sh ${PREV_TAG} ${NEW_TAG}"
    CMD_PREVIEW=(gh release create "$NEW_TAG" --verify-tag --latest --notes-file "<generated>")
  fi
  if ((${#PASS_THROUGH[@]} > 0)); then
    for _arg in "${PASS_THROUGH[@]}"; do
      CMD_PREVIEW+=("$_arg")
    done
  fi
  printf "[Dry run] Would run:"
  printf " %q" "${CMD_PREVIEW[@]}"
  printf "\n"
  exit 0
fi

"$ROOT_DIR/scripts/bump_version.sh" "$BUMP_TYPE"

read_version="$(sed -nE 's/^__version__ *= *"([0-9]+\.[0-9]+\.[0-9]+)"/\1/p' "$VERSION_FILE")"
if [[ "$read_version" != "$new_version" ]]; then
  echo "error: expected ${VERSION_FILE} to be ${new_version} after bump; got \"${read_version}\"." >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "error: Bump and push succeeded (${NEW_TAG}); gh is missing. Install GitHub CLI, then either:" >&2
  echo "  gh release create ${NEW_TAG} --verify-tag --generate-notes --latest" >&2
  echo "  or: scripts/gh_release_latest_tag.sh" >&2
  exit 1
fi

git fetch origin --tags

CURRENT="$(git symbolic-ref --short HEAD 2>/dev/null || true)"
HASH_HEAD="$(git rev-parse HEAD)"
HASH_TAG="$(git rev-parse "${NEW_TAG}^{}" 2>/dev/null || true)"
if [[ -z "$HASH_TAG" ]]; then
  echo "error: tag \"${NEW_TAG}\" not found after bump_version.sh." >&2
  exit 1
fi

if gh release view "$NEW_TAG" >/dev/null 2>&1; then
  echo "error: GitHub release for \"$NEW_TAG\" already exists (after bump)." >&2
  echo "  gh release view $NEW_TAG" >&2
  exit 1
fi

if [[ -n "${CURRENT:-}" && "$HASH_HEAD" != "$HASH_TAG" ]]; then
  echo "note: current branch (${CURRENT}) HEAD differs from ${NEW_TAG} commit; gh still targets the tagged commit." >&2
fi

NOTES_FILE=""
cleanup_notes_file() {
  if [[ -n "${NOTES_FILE:-}" && -f "$NOTES_FILE" ]]; then
    rm -f "$NOTES_FILE"
  fi
}
trap cleanup_notes_file EXIT

CMD=(gh release create "$NEW_TAG" --verify-tag --latest)

if [[ "$SKIP_AI_NOTES" == true ]]; then
  echo "Generating release notes with gh --generate-notes…"
  CMD+=(--generate-notes)
else
  echo "Generating release notes with Cursor agent (${PREV_TAG}..${NEW_TAG})…"
  if NOTES_FILE="$(generate_release_notes_file "$PREV_TAG" "$NEW_TAG")"; then
    echo "--- Release notes preview ---"
    cat "$NOTES_FILE"
    echo "-----------------------------"
    CMD+=(--notes-file "$NOTES_FILE")
  else
    echo "warning: Cursor agent release-notes generation failed; falling back to gh --generate-notes." >&2
    echo "  Ensure \`cursor agent login\` (or \`agent login\`) succeeded, or pass --skip-ai-notes." >&2
    CMD+=(--generate-notes)
  fi
fi

if ((${#PASS_THROUGH[@]} > 0)); then
  for _arg in "${PASS_THROUGH[@]}"; do
    CMD+=("$_arg")
  done
fi

"${CMD[@]}"
echo "Done: released ${NEW_TAG} on GitHub."
