#!/usr/bin/env bash
# Create a GitHub Release for the latest git tag (semver-sorted) using gh CLI.
# Release notes are generated by the Cursor agent CLI from commits between the previous tag and the latest tag.
# Publishing triggers .github/workflows/release-desktop.yml when the workflow is enabled on the repo.
# To bump version, push the new tag, and create that release in one step, use scripts/bump_and_release.sh.
#
# Prerequisites:
#   - gh authenticated (gh auth login), git, tags pushed to GitHub (--verify-tag)
#   - Cursor agent CLI logged in (cursor agent login or agent login) unless --skip-ai-notes
#
# Usage:
#   scripts/gh_release_latest_tag.sh
#   scripts/gh_release_latest_tag.sh --no-fetch
#   scripts/gh_release_latest_tag.sh --dry-run
#   scripts/gh_release_latest_tag.sh --skip-ai-notes
#   scripts/gh_release_latest_tag.sh -- --draft --notes "Smoke test build"
#
# Env:
#   FETCH_TAGS=0              — skip "git fetch origin --tags"
#   SKIP_AI_RELEASE_NOTES=1   — use gh --generate-notes instead of Cursor agent
#   CURSOR_AGENT_MODEL        — optional model for release-notes generation

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
  echo "error: run this from inside the dronmakr git repository." >&2
  exit 1
}
cd "$REPO_ROOT"

FETCH_TAGS="${FETCH_TAGS:-1}"
NO_FETCH=false
DRY_RUN=false
SKIP_AI_NOTES=false
PASS_THROUGH=()

generate_release_notes_file() {
  local prev_tag=$1
  local new_tag=$2
  local notes_file
  notes_file="$(mktemp "${TMPDIR:-/tmp}/dronmakr-release-notes.XXXXXX")"
  if "$REPO_ROOT/scripts/generate_release_notes.sh" "$prev_tag" "$new_tag" > "$notes_file"; then
    if [[ -s "$notes_file" ]]; then
      echo "$notes_file"
      return 0
    fi
  fi
  rm -f "$notes_file"
  return 1
}

while (($#)); do
  case "$1" in
    --no-fetch) NO_FETCH=true; shift ;;
    --dry-run) DRY_RUN=true; shift ;;
    --skip-ai-notes) SKIP_AI_NOTES=true; shift ;;
    --)
      shift
      PASS_THROUGH+=("$@")
      break
      ;;
    *)
      PASS_THROUGH+=("$1")
      shift
      ;;
  esac
done

if ! command -v gh >/dev/null 2>&1; then
  echo "error: gh (GitHub CLI) is not installed or not on PATH." >&2
  exit 1
fi

if [[ "$NO_FETCH" == false && "$FETCH_TAGS" != "0" ]]; then
  echo "Fetching tags from origin…"
  git fetch origin --tags
fi

# Newest tag by version refname (--sort=-version:refname is Git-aware semver-ish ordering).
TAG="$(git tag -l --sort=-version:refname | head -n1)" || true
PREV_TAG="$(git tag -l --sort=-version:refname | sed -n '2p')" || true
if [[ -z "${TAG:-}" ]]; then
  echo "error: no tags found locally. Create and push a tag first, e.g. git tag v0.46.0 && git push origin v0.46.0" >&2
  exit 1
fi

if [[ "${SKIP_AI_RELEASE_NOTES:-}" == "1" ]]; then
  SKIP_AI_NOTES=true
fi

CURRENT="$(git symbolic-ref --short HEAD 2>/dev/null || true)"
HASH_TAG="$(git rev-parse "$TAG^{}" 2>/dev/null || true)"
HASH_HEAD="$(git rev-parse HEAD)"

if gh release view "$TAG" >/dev/null 2>&1; then
  echo "error: GitHub release for tag \"$TAG\" already exists. View: gh release view $TAG" >&2
  exit 1
fi

echo "Latest tag by version sort: $TAG"
if [[ -n "${PREV_TAG:-}" ]]; then
  echo "Previous tag: $PREV_TAG"
else
  echo "note: no previous tag found; AI release notes require at least two tags." >&2
fi
if [[ -n "${CURRENT:-}" && "$HASH_HEAD" != "$HASH_TAG" ]]; then
  echo "note: current branch HEAD ($CURRENT) differs from tag $TAG; the release metadata still points at the tag commit." >&2
fi

if [[ "$DRY_RUN" == true ]]; then
  if [[ "$SKIP_AI_NOTES" == true || -z "${PREV_TAG:-}" ]]; then
    echo "[Dry run] Would generate release notes: gh --generate-notes"
    CMD=(gh release create "$TAG" --verify-tag --generate-notes --latest)
  else
    echo "[Dry run] Would generate release notes: scripts/generate_release_notes.sh ${PREV_TAG} ${TAG}"
    CMD=(gh release create "$TAG" --verify-tag --latest --notes-file "<generated>")
  fi
  if ((${#PASS_THROUGH[@]} > 0)); then
    for _arg in "${PASS_THROUGH[@]}"; do
      CMD+=("$_arg")
    done
  fi
  printf "Would run:"
  printf " %q" "${CMD[@]}"
  printf "\n"
  exit 0
fi

NOTES_FILE=""
cleanup_notes_file() {
  if [[ -n "${NOTES_FILE:-}" && -f "$NOTES_FILE" ]]; then
    rm -f "$NOTES_FILE"
  fi
}
trap cleanup_notes_file EXIT

CMD=(gh release create "$TAG" --verify-tag --latest)

if [[ "$SKIP_AI_NOTES" == true || -z "${PREV_TAG:-}" ]]; then
  if [[ -z "${PREV_TAG:-}" && "$SKIP_AI_NOTES" != true ]]; then
    echo "Generating release notes with gh --generate-notes (no previous tag)…"
  else
    echo "Generating release notes with gh --generate-notes…"
  fi
  CMD+=(--generate-notes)
else
  echo "Generating release notes with Cursor agent (${PREV_TAG}..${TAG})…"
  if NOTES_FILE="$(generate_release_notes_file "$PREV_TAG" "$TAG")"; then
    echo "--- Release notes preview ---"
    cat "$NOTES_FILE"
    echo "-----------------------------"
    CMD+=(--notes-file "$NOTES_FILE")
  else
    echo "warning: Cursor agent release-notes generation failed; falling back to gh --generate-notes." >&2
    echo "  Ensure \`cursor agent login\` (or \`agent login\`) succeeded, or pass --skip-ai-notes." >&2
    CMD+=(--generate-notes)
  fi
fi

# Bash 3.2 + set -u: "${empty[@]}" is an unbound-variable error — only append when non-empty.
if ((${#PASS_THROUGH[@]} > 0)); then
  for _arg in "${PASS_THROUGH[@]}"; do
    CMD+=("$_arg")
  done
fi

exec "${CMD[@]}"
